name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy-staging:
    environment: Staging
    runs-on: ubuntu-latest
    
    env:
      SSH_HOST: ${{ secrets.SERVER_HOST }}
      SSH_USER: ${{ secrets.SERVER_USER }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.REMOTE_PATH }}
            git pull origin ${{ github.ref_name }}
            sudo chown -R bitnami:bitnami .
            docker-compose exec -T web pip install -r requirements.txt
            docker-compose exec -T web python manage.py migrate --noinput
            docker-compose exec -T web python manage.py collectstatic --noinput
            sudo /opt/bitnami/ctlscript.sh restart apache || true

  deploy-production:
    needs: deploy-staging
    environment: Production
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SERVER_HOST }}
      SSH_USER: ${{ secrets.SERVER_USER }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
    steps:
      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.SSH_HOST }}
          username: ${{ env.SSH_USER }}
          key: ${{ env.SSH_KEY }}
          port: 22
          script: |
            cd ${{ env.REMOTE_PATH }}
            git pull origin main
            sudo chown -R bitnami:bitnami .
            docker-compose exec -T web pip install -r requirements.txt
            docker-compose exec -T web python manage.py migrate --noinput
            docker-compose exec -T web python manage.py collectstatic --noinput
            sudo /opt/bitnami/ctlscript.sh restart apache || true