name: Deploy CI

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    environment: Staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd ${{ secrets.REMOTE_PATH }}
            git pull origin ${{ github.ref_name }}
            sudo chown -R bitnami:bitnami .
            docker-compose exec -T web pip install -r requirements.txt
            docker-compose exec -T web python manage.py migrate --noinput
            docker-compose exec -T web python manage.py collectstatic --noinput
            sudo /opt/bitnami/ctlscript.sh restart apache || true